M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat 20 Sep 2025 02:23:52 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-20T14:23:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X128.6Y-69.61
X128.6Y-75.39
X128.6Y-94.61
X128.6Y-100.39
T0
M30
